export const createDemoInvoice = (defaults = {}) => ({
  confidence: "medium",
  vendorName: "Apex Office Supplies Pvt Ltd",
  invoiceNumber: "INV-2048",
  invoiceDate: "2026-03-27",
  dueDate: "2026-04-11",
  vendorGstin: "27AAECA1234F1ZQ",
  subtotal: 42500,
  cgst: 3825,
  sgst: 3825,
  igst: 0,
  total: 50150,
  lineItems: [
    {
      id: "line-1",
      description: "Laser printer cartridge set",
      hsnSacCode: "8443",
      quantity: 3,
      rate: 6000,
      amount: 18000,
    },
    {
      id: "line-2",
      description: "A4 copier paper carton",
      hsnSacCode: "4802",
      quantity: 10,
      rate: 1250,
      amount: 12500,
    },
    {
      id: "line-3",
      description: "Desktop stationery refill kit",
      hsnSacCode: "4820",
      quantity: 8,
      rate: 1500,
      amount: 12000,
    },
  ],
  reviewNotes: [
    "Vendor GSTIN is readable but should still be checked against the original invoice.",
    "Due date was inferred from credit terms shown near the footer.",
  ],
  tallyConfig: {
    companyName: "Prototype Company",
    purchaseLedgerName: defaults.purchaseLedgerName || "Purchase A/c",
    cgstLedgerName: defaults.cgstLedgerName || "Input CGST",
    sgstLedgerName: defaults.sgstLedgerName || "Input SGST",
    igstLedgerName: defaults.igstLedgerName || "Input IGST",
  },
});

export const createDemoBankStatement = (defaults = {}) => ({
  confidence: "medium",
  summary: {
    periodStart: "2026-03-01",
    periodEnd: "2026-03-31",
    totalDebits: 146850,
    totalCredits: 218500,
    transactionCount: 6,
    reviewCount: 2,
  },
  transactions: [
    {
      id: "txn-1",
      date: "2026-03-03",
      narration: "NEFT SALARY CREDIT ACME CONSULTING LLP",
      reference: "N567812",
      debit: 0,
      credit: 85000,
      balance: 245120,
      amount: 85000,
      ledgerHead: "Salary",
      confidence: "high",
      needsReview: false,
      voucherType: "Receipt",
      debitAccount: "Bank Account",
      creditAccount: "Salary",
    },
    {
      id: "txn-2",
      date: "2026-03-05",
      narration: "UPI/DR/RENT-MARCH/OFFICE-SPACE",
      reference: "UPI98213",
      debit: 28000,
      credit: 0,
      balance: 217120,
      amount: 28000,
      ledgerHead: "Rent",
      confidence: "high",
      needsReview: false,
      voucherType: "Payment",
      debitAccount: "Rent",
      creditAccount: "Bank Account",
    },
    {
      id: "txn-3",
      date: "2026-03-08",
      narration: "ACH DR ELECTRICITY BOARD BILL",
      reference: "ACH44810",
      debit: 9650,
      credit: 0,
      balance: 207470,
      amount: 9650,
      ledgerHead: "Electricity",
      confidence: "high",
      needsReview: false,
      voucherType: "Payment",
      debitAccount: "Electricity",
      creditAccount: "Bank Account",
    },
    {
      id: "txn-4",
      date: "2026-03-12",
      narration: "IMPS TO OWN ACCOUNT TRANSFER",
      reference: "IMPS1102",
      debit: 45000,
      credit: 0,
      balance: 162470,
      amount: 45000,
      ledgerHead: "Transfer to Own Account",
      confidence: "medium",
      needsReview: false,
      voucherType: "Contra",
      debitAccount: "Transfer to Own Account",
      creditAccount: "Bank Account",
    },
    {
      id: "txn-5",
      date: "2026-03-18",
      narration: "UPI DR MANOJ TRADERS",
      reference: "UPI34901",
      debit: 12100,
      credit: 0,
      balance: 150370,
      amount: 12100,
      ledgerHead: "Sundry Creditor",
      confidence: "low",
      needsReview: true,
      voucherType: "Payment",
      debitAccount: "Sundry Creditor",
      creditAccount: "Bank Account",
    },
    {
      id: "txn-6",
      date: "2026-03-26",
      narration: "CASH DEP BY SELF",
      reference: "BR22019",
      debit: 0,
      credit: 133500,
      balance: 283870,
      amount: 133500,
      ledgerHead: "Cash Deposit",
      confidence: "low",
      needsReview: true,
      voucherType: "Contra",
      debitAccount: "Bank Account",
      creditAccount: "Cash Deposit",
    },
  ],
  reviewNotes: [
    "Cash deposit may need to be mapped to Capital Account instead, depending on the source.",
    "Vendor name in UPI narration is abbreviated, so the ledger should be reviewed manually.",
  ],
  tallyConfig: {
    companyName: "Prototype Company",
    bankLedgerName: defaults.bankLedgerName || "Bank Account",
  },
  learningSummary: {
    learnedRuleCount: 0,
    recentInstructions: [],
  },
});
