const ledgerHeads = [
  { name: "Salary", parent: "Indirect Expenses" },
  { name: "Wages", parent: "Direct Expenses" },
  { name: "Rent", parent: "Indirect Expenses" },
  { name: "Electricity", parent: "Indirect Expenses" },
  { name: "Internet Charges", parent: "Indirect Expenses" },
  { name: "Telephone Expenses", parent: "Indirect Expenses" },
  { name: "Office Expenses", parent: "Indirect Expenses" },
  { name: "Printing & Stationery", parent: "Indirect Expenses" },
  { name: "Postage & Courier", parent: "Indirect Expenses" },
  { name: "Travelling Expenses", parent: "Indirect Expenses" },
  { name: "Conveyance", parent: "Indirect Expenses" },
  { name: "Fuel Expenses", parent: "Indirect Expenses" },
  { name: "Repairs & Maintenance", parent: "Indirect Expenses" },
  { name: "Professional Fees", parent: "Indirect Expenses" },
  { name: "Audit Fees", parent: "Indirect Expenses" },
  { name: "Legal Charges", parent: "Indirect Expenses" },
  { name: "Consultancy Charges", parent: "Indirect Expenses" },
  { name: "Marketing Expenses", parent: "Indirect Expenses" },
  { name: "Advertisement", parent: "Indirect Expenses" },
  { name: "Freight & Cartage", parent: "Direct Expenses" },
  { name: "Packing Charges", parent: "Direct Expenses" },
  { name: "Commission Paid", parent: "Indirect Expenses" },
  { name: "Insurance", parent: "Indirect Expenses" },
  { name: "Bank Charges", parent: "Indirect Expenses" },
  { name: "Interest on Loan", parent: "Indirect Expenses" },
  { name: "EMI", parent: "Loans (Liability)" },
  { name: "Loan Account", parent: "Loans (Liability)" },
  { name: "GST Payment", parent: "Duties & Taxes" },
  { name: "TDS Payment", parent: "Duties & Taxes" },
  { name: "Advance Tax", parent: "Duties & Taxes" },
  { name: "Income Tax", parent: "Duties & Taxes" },
  { name: "Cash Withdrawal", parent: "Cash-in-Hand" },
  { name: "Cash Deposit", parent: "Cash-in-Hand" },
  { name: "UPI Transfer", parent: "Bank Accounts" },
  { name: "Card Settlement", parent: "Bank Accounts" },
  { name: "POS Collection", parent: "Bank Accounts" },
  { name: "Transfer to Own Account", parent: "Bank Accounts" },
  { name: "Transfer from Own Account", parent: "Bank Accounts" },
  { name: "Sundry Creditor", parent: "Sundry Creditors" },
  { name: "Sundry Debtor", parent: "Sundry Debtors" },
  { name: "Purchase", parent: "Purchase Accounts" },
  { name: "Sales", parent: "Sales Accounts" },
  { name: "Capital Account", parent: "Capital Account" },
  { name: "Drawings", parent: "Capital Account" },
  { name: "Partner Remuneration", parent: "Indirect Expenses" },
  { name: "Partner Capital", parent: "Capital Account" },
  { name: "Director Salary", parent: "Indirect Expenses" },
  { name: "Cash", parent: "Cash-in-Hand" },
  { name: "Petty Cash", parent: "Cash-in-Hand" },
  { name: "Computer Expenses", parent: "Indirect Expenses" },
  { name: "Software Subscription", parent: "Indirect Expenses" },
  { name: "Cloud Hosting", parent: "Indirect Expenses" },
  { name: "GST Refund", parent: "Duties & Taxes" },
  { name: "Interest Income", parent: "Indirect Incomes" },
  { name: "Miscellaneous Income", parent: "Indirect Incomes" },
  { name: "Miscellaneous Expenses", parent: "Indirect Expenses" },
  { name: "Owner Contribution", parent: "Capital Account" },
  { name: "Customer Receipt", parent: "Sundry Debtors" },
  { name: "Vendor Payment", parent: "Sundry Creditors" },
  { name: "Loan Repayment", parent: "Loans (Liability)" },
  { name: "Credit Card Payment", parent: "Current Liabilities" },
  { name: "Maintenance Charges", parent: "Indirect Expenses" },
  { name: "Security Charges", parent: "Indirect Expenses" },
  { name: "Water Charges", parent: "Indirect Expenses" },
  { name: "Donation", parent: "Indirect Expenses" },
  { name: "Subscription Fees", parent: "Indirect Expenses" },
];

const defaultVoucherLedgers = {
  purchaseLedgerName: "Purchase A/c",
  cgstLedgerName: "Input CGST",
  sgstLedgerName: "Input SGST",
  igstLedgerName: "Input IGST",
  bankLedgerName: "Bank Account",
};

module.exports = {
  ledgerHeads,
  defaultVoucherLedgers,
};
